server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quickform}
    username: ${DB_USER:quickform}
    password: ${DB_PASS:quickform}
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.quickform.api.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.quickform: DEBUG
